source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'RxViewModel_Tests', :exclusive => true do
  pod "RxViewModel", :path => "../"

  pod 'RxCocoa', '~> 2.0.0-alpha.3'
  pod 'RxSwift', '~> 2.0.0-alpha.3'
  pod 'Quick', '~> 0.6.0'
  pod 'Nimble', '2.0.0-rc.3'
end
