source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'RxViewModel_Tests', :exclusive => true do
  pod "RxViewModel", :path => "../"

  pod 'RxCocoa', :git => 'https://github.com/kzaher/RxSwift', :branch => 'feature/swift2.0'
  pod 'RxSwift',   :git => 'https://github.com/kzaher/RxSwift', :branch => 'feature/swift2.0'
  pod 'Quick', :git => 'https://github.com/Quick/Quick', :branch => 'swift-2.0'
  pod 'Nimble', :git => 'https://github.com/Quick/Nimble', :branch => 'swift-2.0'
end
