source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'RxViewModel_Tests', :exclusive => true do
  pod "RxViewModel", :path => "../"

  pod 'RxCocoa', '~> 2.0.0-alpha.3'
  pod 'RxSwift', '~> 2.0.0-alpha.3'
  pod 'Quick', :git => 'https://github.com/Quick/Quick', :branch => 'swift-2.0'
  pod 'Nimble', :git => 'https://github.com/Quick/Nimble', :branch => 'swift-2.0'
end
