source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!

# Test Libraries
def test_pods
  pod 'Quick'
  pod 'Nimble'
end

def library
  pod 'RxViewModel', :path => "../"
end

target 'Demo' do
  platform :ios, '9.0'
  library

  target 'RxViewModelTests-iOS' do
      platform :ios, '9.0'
      inherit! :search_paths

      test_pods
  end
end

target 'RxViewModelTests-tvOS' do
    platform :tvos, '9.0'
    library

    test_pods
end

target 'RxViewModelTests-macOS' do
    platform :osx, '10.10'
    library

    test_pods
end
